In [6]:
import torch

In [7]:
a = torch.tensor(([3,4],[5,6]))
b = torch.tensor(([6,7], [8,9]))
print('tensor 加法：', a + b)

tensor 加法： tensor([[ 9, 11],
        [13, 15]])


In [8]:
# 减法
print('tensor 减法', a - b)

tensor 减法 tensor([[-3, -3],
        [-3, -3]])


In [9]:
# 乘法
print(a * b)

tensor([[18, 28],
        [40, 54]])


In [10]:
# 除法
print(a / b)

tensor([[0.5000, 0.5714],
        [0.6250, 0.6667]])


In [11]:
# 张量矩阵乘法1（行 * 列）
print( torch.matmul(a, b))

tensor([[50, 57],
        [78, 89]])


In [12]:
# 张量矩阵乘法2（全量）
print(a @ b)

tensor([[50, 57],
        [78, 89]])


In [16]:
# 张量拼接 cat（dim = 0 按照第一个维度，行拼接，dim = 1 按照第二个维度，列拼接）
# dim 为dimension，dim若为-1时，表示为最后一个，若为-2，则为倒数第二个
print(torch.cat((a,b), dim = 1))

print(torch.cat((a,b), dim = -2))

tensor([[3, 4, 6, 7],
        [5, 6, 8, 9]])
tensor([[3, 4],
        [5, 6],
        [6, 7],
        [8, 9]])
