In [2]:
import torch

In [ ]:
# 创建一个未初始化的张量
# 虽然输出结果中存在值，但这只是torch在内存中划出了一块空间给你，不会清理这块空间中原始数据
x = torch.empty(3, 2)
x

tensor([[-6.2119e-33,  1.0748e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])

In [ ]:
# 创建正太分布的张量，randn中的 n 为 normal（正态）的意思
# 正太分布的张量创建均值为0， 标准差为1
x = torch.randn(3,2)
x

tensor([[ 1.2704, -0.7135],
        [ 1.0786, -0.3698],
        [ 0.0518,  0.8728]])

In [11]:
# 创建全零的张量
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
# 5、指定张量类型创建张量
x = torch.tensor([2,4], dtype = torch.long)
print('创建x指定数据类型为long得到的结果为：',x)
y = torch.tensor([4,5], dtype = torch.float32)
print('创建y指定数据类型为float32得到的结果为：',y)
z = torch.tensor([1,2], dtype = torch.int64)
print('创建z指定数据类型为int64得到的结果为：', z)


创建x指定数据类型为long得到的结果为： tensor([2, 4])
创建y指定数据类型为float32得到的结果为： tensor([4., 5.])
创建z指定数据类型为int64得到的结果为： tensor([1, 2])


In [ ]:
# 6、指定张量数据创建张量
x = torch.tensor([[1, 3, 4],[4, 1, 4],[2,6,5]])
x

In [21]:
# 7、创建全 1 的张量
r = torch.ones(4, 5)
r

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [23]:
x = torch.rand(3, 4)
print('创建 x 的张量为：', x)
# 8、创建一个形状一样的张量
y = torch.rand_like(x)
print('创建新的张量 y 为：', y)
# 形状一样，但内容为全1 或 全0 的张量
z = torch.ones_like(x)
print('创建全 1 的张量为：', z)

q = torch.zeros_like(x)
print('创建全 0 的张量为：', q)


创建 x 的张量为： tensor([[0.5618, 0.3005, 0.2671, 0.2104],
        [0.5613, 0.8066, 0.6843, 0.4119],
        [0.2659, 0.2831, 0.6266, 0.2367]])
创建新的张量 y 为： tensor([[0.3989, 0.5457, 0.7821, 0.3432],
        [0.9051, 0.4436, 0.1468, 0.2174],
        [0.4290, 0.6830, 0.6796, 0.9404]])
创建全 1 的张量为： tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
创建全 0 的张量为： tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [27]:
# 9、创建形状一样，内容全为指定内容的张量
x = torch.rand(2, 4)

y = torch.full_like(x, 1)
y

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
# 10、创建多维数组
x = torch.tensor([[2,3],[5,1],[0.6, 7]])

# 当前张量类型
print('当前张量类型为：', type(x))
# 当前张量中元素类型
print('当前张量中元素类型为：', x.dtype)

当前张量类型为： <class 'torch.Tensor'>
当前张量中元素类型为： torch.float32
